import { createElement } from '@lwc/engine-dom';
import Ds_PortalUBOTreeDiagramViewOnly from 'c/ds_PortalUBOTreeDiagramViewOnly';

describe('c-ds-portal-ubo-tree-diagram-view-only', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ds-portal-ubo-tree-diagram-view-only', {
            is: Ds_PortalUBOTreeDiagramViewOnly
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});